baseurl = "https://fsamin.github.io/blog/"
languageCode = "en"
title = "blog"
author = "François Samin"
copyright = "François Samin -  All rights reserved."

[params]
  logo      = "/images/logo.jpg"
  twitter   = "https://twitter.com/francoissamin"
  github    = "https://github.com/fsamin/"
  email     = "francois.samin+blog@gmail.com"
  analytics = "UA-88062507-1"
